### ISSUE TITLE
Weird issue when requesting body plot

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyansys-geometry#1249]
Seems like a body plot is not working for some reason... https://geometry.docs.pyansys.com/version/stable/examples/01_getting_started/05_plotter_picker.html#Plot-objects

@AlejandroFernandezLuces could you investigate?

**Comment by RobPasMue** [comment]
Neither is clipping working I believe

**Comment by RobPasMue** [comment]
As a reference you can use https://geometry.docs.pyansys.com/version/0.5/examples/01_getting_started/05_plotter_picker.html

**Comment by AlejandroFernandezLuces** [comment]
That's weird... I'll take a look

**Comment by RobPasMue** [comment]
Thanks @AlejandroFernandezLuces!

**Comment by RobPasMue** [comment]
Thanks for the fix!
