### ISSUE TITLE
Deprecated APIs should still be available for a few releases

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyansys-geometry#1259]
We removed some APIs that might have been critical to certain users like ``face_normal()``, ``PlotterHelper``...

We should deprecate them properly if possible via decorators.

**Comment by MaxJPRey** [comment]
Ideally we should support the 2 last major release.

**Comment by RobPasMue** [comment]
It is not related to the product, it is related to the Python APIs mostly.

**Comment by MaxJPRey** [comment]
Yes, but still if people used them, I would suggest to let the deprecation warning -using decorator- for quite few quarters.
