### ISSUE TITLE
Add server exit to del operator and finished process 

### ISSUE THREAD

**Issue by dkowollik** [ansys/pyansys-geometry#1415]
### 📝 Description of the feature

Hi, 

can you please at the server exit to the python `del` operator and once a python process is finished? PyACP makes use of the Python stdlib `weakref.finalize`. The callback is executed, if the instance is not referenced anymore or if the python process ends.

**Comment by dkowollik** [comment]
Hi @RobPasMue,

I understand. I am launching by the same python terminal. I meant something different. If I use a script and forget to implement the `modeler.exit()` or `modeler.close()`, the server keeps on running and blocks licenses. In PyMAPDL and PyACP they stop the server, even if you launched during this python process and forget to call exit or close.  
In PyACP `del modeler` would also close the server.

**Comment by RobPasMue** [comment]
Aha, gotcha! For sure, let me implement that. =)

**Comment by RobPasMue** [comment]
PR coming up @dkowollik - see #1417. This should make sure every time there is a client connection, it is closed.
