### ISSUE TITLE
SpaceClaim is always opened in Parasolid mode.

### ISSUE THREAD

**Issue by Alberto-DM** [ansys/pyansys-geometry#1439]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

SpaceClaim can be opened in Parasolid mode (able to save only scdocx) or ACIS mode (able to save scdoc files). 
The choice can be made with the environment variable `SPACECLAIM_MODE`. 
If it is =1 or not present, SC opens in ACIS mode. If it is =2, it opens in Parasolid mode. 
The method `launch_modeler_with_spaceclaim` always sets the variable `SPACECLAIM_MODE=2`.
PyGeometry should honor the existing environment variable if it is already set in the system.
The current behavior brakes the code developed for the Ericsson EVDE program, preventing us to upgrade to version 2024R2.

### 📝 Steps to reproduce

1. Set the env variable `SPACECLAIM_MODE=1`
2. Launch SpaceClaim with the method launch_modeler_with_spaceclaim
3. Verify that SpaceClaim only supports scdocx documents.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aiosignal==1.3.1
annotated-types==0.7.0
ansys-api-dbu==0.3.4
ansys-api-geometry==0.4.8
ansys-geometry-core==0.7.2
ansys-pythonnet==3.1.0rc3
ansys-tools-path==0.4.1
ansys-tools-visualization-interface==0.4.4
async-timeout==4.0.3
attrs==24.2.0
beartype==0.17.2
bottle==0.12.25
build==1.1.1
cachetools==5.3.3
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
clr-loader==0.2.6
colorama==0.4.6
contourpy==1.2.0
cycler==0.12.1
defusedxml==0.7.1
exceptiongroup==1.2.2
fonttools==4.50.0
fpdf2==2.7.9
frozenlist==1.4.1
google-api-core==2.18.0
google-api-python-client==2.123.0
google-auth==2.29.0
google-auth-httplib2==0.2.0
googleapis-common-protos==1.63.0
grpcio==1.62.1
grpcio-health-checking==1.48.2
httplib2==0.22.0
idna==3.6
iniconfig==2.0.0
jsonformatter==0.3.2
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
matplotlib==3.8.3
more-itertools==10.5.0
msgpack==1.1.0
multidict==6.1.0
numpy==1.26.4
packaging==24.0
pandas==2.2.3
pillow==10.2.0
Pint==0.23
platformdirs==4.2.0
pluggy==1.5.0
plumbum==1.8.2
pooch==1.8.1
proto-plus==1.23.0
protobuf==3.20.3
psutil==5.9.8
pyaedt==0.10.2
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==2.9.2
pydantic_core==2.23.4
pyedb==0.28.0
pyparsing==3.1.2
pyproject_hooks==1.0.0
pytest==8.3.3
python-dateutil==2.9.0.post0
pytomlpp==1.0.13
pytz==2024.2
pyvista==0.43.4
pywin32==306
PyYAML==6.0.2
referencing==0.35.1
requests==2.31.0
rpds-py==0.20.0
rpyc==6.0.0
rsa==4.9
Rtree==1.3.0
scikit-rf==1.3.0
scipy==1.12.0
scooby==0.9.2
semver==3.0.2
six==1.16.0
toml==0.10.2
tomli==2.0.1
trame==3.6.5
trame-client==3.3.1
trame-server==3.2.3
trame-vtk==2.8.10
trame-vuetify==2.7.1
typing_extensions==4.10.0
tzdata==2024.2
uritemplate==4.1.1
urllib3==2.2.1
vtk==9.3.0
websockets==13.1
wslink==2.2.1
yarl==1.12.1
```

**Comment by RobPasMue** [comment]
Easy fix - working on this.
