### ISSUE TITLE
Implement API to extract server logs easily from GRPCClient/Modeler

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyansys-geometry#1514]
We have means of requesting actively the server logs. Let's make use of it and enable it for users to consume easily.

**Comment by MaxJPRey** [comment]
Excellent.
I expect, you would be able to select, debug/info/error... and other field to be able to perform some operations around the log.
This could be helpful for debug.

**Comment by RobPasMue** [comment]
Yes that was already possible. When launching the service you can configure it's logging level. With this approach (see #1515) we will be able to request them remotely, see them as string or dump it to file, retrieve all logs on the server etc.
