### ISSUE TITLE
Add API for geometry cleanup operations

### ISSUE THREAD

**Issue by chadqueen** [ansys/pyansys-geometry#195]
Identify the key model cleanup tools users require and expose them as design/component/body operations as appropriate.

Server-side support required before this can be implemented.

**Comment by RobPasMue** [comment]
We'll link this to #648 for now. However, it is "half-way" implemented. We need to actually pass in ``Design``, ``Component``, ``Body`` objects... and not just strings that represent their IDs. Good thing is that this is an "independent" submodule of the package
