### ISSUE TITLE
Modify version tag referring to service instance to platform type

### ISSUE THREAD

**Issue by rajesh1359** [ansys/pyansys-geometry#478]
### Description of the modifications

Currently launch_remote_modeler function takes **version** argument as platform version "linux" or "windows". The request is to add another argument '**platform**' for taking these input and version argument can continue to take service version "231" etc.

I could have created a PR for change but we may need to streamline things in source code as well. So creating this issue.

https://geometry.docs.pyansys.com/version/dev/autoapi/ansys/geometry/core/connection/launcher/index.html#ansys.geometry.core.connection.launcher.launch_remote_modeler

### Useful links and references

https://geometry.docs.pyansys.com/version/dev/autoapi/ansys/geometry/core/connection/launcher/index.html#ansys.geometry.core.connection.launcher.launch_remote_modeler

**Comment by RobPasMue** [comment]
@rajesh1359 we finally got around to do this - merged in #1416. Will be released shortly (0.7.2)
