### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyansys-geometry#788]
Related to #787 - we tried it but ``vtk`` was blocking the update.

**Comment by ChristosT** [comment]
Great to see interest for python 3.12 so early ! The latest [rc](https://pypi.org/project/vtk/9.3.0rc2/ )  comes with python 3.12 support. Could you give it a try and report related issues at
https://gitlab.kitware.com/vtk/vtk/-/issues ?

**Comment by RobPasMue** [comment]
Okay sounds like it "works" :)

We are only doing smoke testing - checking that the package builds and that we are able to import its version. Our main dev versions are Python 3.9 to 3.11. This is just to provide support for Python 3.12 on a best-effort basis. Thanks @ChristosT for pointing out the current 9.0.3rc2 release.

I am curious... when is the actual 9.3.0 release expected?

**Comment by ChristosT** [comment]
That's hard to tell . Depends on how the rc goes and if any issues are reported. If everything goes well the final release should be in a few weeks.

**Comment by MaxJPRey** [comment]
Thanks @RobPasMue for taking care of this first set of testing. It will be halpful for all our other repos.

**Comment by ChristosT** [comment]
> I am curious... when is the actual 9.3.0 release expected?

vtk 9.3.0 is available on [pypi](https://pypi.org/project/vtk/)

**Comment by RobPasMue** [comment]
Yep!! Dependabot was so kind that opened #854 for us =) Thanks @ChristosT!
