### ISSUE TITLE
Document plots are static

### ISSUE THREAD

**Issue by AlejandroFernandezLuces** [ansys/pyansys-geometry#845]
Due to #842 , I opened this PR #843 to temporarily show a screenshot of the plots, while we don't find the error. This should be reverted as soon as we find out the error or when https://github.com/ansys-internal/kitware-ansys/issues/20 is fixed.

**Comment by RobPasMue** [comment]
This is a duplicate of #697

**Comment by AlejandroFernandezLuces** [comment]
Let's close this one then
