### ISSUE TITLE
``script_args`` should be an optional argument on ``run_discovery_script_file`` argument

### ISSUE THREAD

**Issue by XIAO-GUO-commint** [ansys/pyansys-geometry#870]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I want to run a script in SpaceClaim using run_discovery_script_file, but I'm unsure what to include in script_args. I have reviewed the original documentation, but it did not provide guidance on how to manage this.

from ansys.geometry.core import launch_modeler_with_spaceclaim

modeler_discovery = launch_modeler_with_spaceclaim()

modeler_discovery.run_discovery_script_file(file_path=r'E:\2023project\nncx\muti-optimize\Mesh_Gem\1.scscript',script_args=script_args)
![image](https://github.com/ansys/pyansys-geometry/assets/83817101/be079645-61aa-4834-b6eb-46f4db973059)

### 📝 Steps to reproduce

I want to run a script in SpaceClaim using run_discovery_script_file, but I'm unsure what to include in script_args. I have reviewed the original documentation, but it did not provide guidance on how to manage this.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23r2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
numpy
pandas
ansys-geometry...
```

**Comment by AlejandroFernandezLuces** [comment]
> Hi @XIAO-GUO-commint - if you do not want to pass in any script arguments then you do not need to pass any. For now, pass in an "empty dictionary" (i.e. `{}`).
> 
> We have to change the method to make `script_args` as optional. @AlejandroFernandezLuces can you take care of this? It is an easy fix. We will do a patch release right afterwards

Sure! I'll take a look.
